### ISSUE TITLE
Spiderfoot Training Video

### ISSUE THREAD

**Issue by Retro64XYZ** [smicallef/spiderfoot#1140]
https://www.youtube.com/watch?v=O8oRvOMaRRk

I created a training and use video for Spiderfoot. Would this be something you all would like to include in the readme or as part of the Spiderfoot website?

If not, please feel free to close this. If you do watch it and see any problems, let me know so I can update or fix. I regularly encourage the use of Spiderfoot in my classes.

Thanks,
Aaron

**Comment by bcoles** [comment]
> I regularly encourage the use of Spiderfoot in my classes.

Good stuff.

> If you do watch it and see any problems, let me know so I can update or fix.

SpiderFoot is an automated all-in-one OSINT tool. In my biased opinion: the best. However, due to the nature of automated OSINT, SpiderFoot works best with accurate and unique scan target data (especially network infrastructure). Unique identifiers such as email addresses are also good. Generally the more precise information you give as a scan target the better results you will get.

Additional tools will be required once a piece of data has been manually verified as useful/relevant. For example, once a GitHub repository, organisation or user have been identified, separate tools should be used to analyse the repository for secrets, scrape the users who have starred the repository, scrape the list of members in the organisation, search for pull requests and issues by the user, scrape the user's followers, etc...

SpiderFoot can (and does) dive deeper in some instances; however, this comes at the cost of decreased accuracy and increased scan duration. SpiderFoot has no method to modify result data and scan scope during a scan (ie, to indicate that an event of type `COMPANY_NAME` with a value of `ACME Corp` is within scope, but `Super ACME Corp South Africa` is not in scope). Each module has module options which can be tweaked, but the default options are generally configured to work well with the pre-configured use cases (Passive, Footprint, Investigate). There is a constant balancing act in adding new modules and setting reasonable default settings while keeping scan duration and false positives to a minimum.

Unfortunately, if you're looking for individuals as per the use-case in your video, it is usually best to perform some initial OSINT first to find potential scan targets such as usernames and email addresses.

Searching for people (referred to as `HUMAN_NAME` data type) will result in a lot of false positives. Finding specific information is best as a starting point (email address, phone number, domain names owned by the person, username, etc).

For example, there's millions of "John Smith" and you'll be swamped with false positives. However, there's only one john.smith.xx420.69xx.360.noscope@gmail.com - this will yield significantly better results.

Of course, you can start with a SpiderFoot scan too! But I end up using a web browser while reviewing the data and find it easier to simply start with a browser and search engines as it is easier to browse (more visual) and won't use up API key quotas. Both approaches will require some manual digging initially until you've identified some potentially viable unique identifiers with which to seed your SpiderFoot scan.

As for the issue you encountered with false positives for social media profiles, unfortunately this comes with the territory. Several people can share the same username.

It's been a while since I watched your video. If I remember correctly, SpiderFoot didn't find any usernames. Instead it generated a potentially valid username by mashing the `HUMAN_NAME` together into a string which *might* be a valid username (by removing invalid characters such as whitespace). This is basically a stab in the dark. It usually leads to false positives but can sometimes be useful.

For scan input data of `USERNAME` type, SpiderFoot primarily uses the [WhatsMyName](https://github.com/WebBreacher/WhatsMyName) [database](https://github.com/WebBreacher/WhatsMyName/blob/master/web_accounts_list.json). I recommend taking a look at WhatsMyName. It is a command line tool to check whether a specific username is registered on a bunch of websites, similar to the [NameChk](https://namechk.com/) website, except slightly better for opsec as you can use proxies and don't have to trust whoever runs NameChk.

[Sherlock](https://github.com/sherlock-project/sherlock) is a very similar tool to [WhatsMyName](https://github.com/WebBreacher/WhatsMyName) and checks for a username on a larger number of websites. These two tools will be useful for your use case and workflow.

I remember you had issues with one website in particular (I forget which one).  If you submit a pull request to fix it to [WhatsMyName](https://github.com/WebBreacher/WhatsMyName) the fix will make its way into SpiderFoot automatically (+24 hours, as the WhatsMyName data is cached for 24 hours before the next update check).
