### ISSUE TITLE
Integration into other database platforms

### ISSUE THREAD

**Issue by wirecutter313** [smicallef/spiderfoot#131]
I would love to see an easy way to get the data into elastic or mysql rather than Sqlite.

**Comment by smicallef** [comment]
It's not really intended as part of the design, because SpiderFoot is intended to be super easy to set up and get running, plus if I spend time integrating with other systems that is less development time spent on integrating with new data feeds. I will soon create a module for sending the events to ElasticSearch, but that won't be used by the front-end.
