### ISSUE TITLE
Error-Failed | Unhandled exception (JSONDecodeError) encountered during scan

### ISSUE THREAD

**Issue by armaanfarshori** [smicallef/spiderfoot#1752]
['Traceback (most recent call last):\n', '  File "/usr/share/spiderfoot/sfscan.py", line 180, in startScan\n    mod.setup(self.ts.sf, self.ts.modconfig[modName])\n', '  File "/usr/share/spiderfoot/modules/sfp_accounts.py", line 80, in setup\n    self.sites = json.loads(content)[\'sites\']\n', '  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads\n    return _default_decoder.decode(s)\n', '  File "/usr/lib/python3.9/json/decoder.py", line 340, in decode\n    raise JSONDecodeError("Extra data", s, end)\n', 'json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)\n']

What version of Python are you using?
Python 3.9.2
What version of SpiderFoot are you using (stable release or Git `master` branch)?
Spiderfoot v3.0

![Screenshot at 2023-02-17 13-25-56](https://user-images.githubusercontent.com/7535252/219585620-6444757d-2699-4d9b-b634-e85b9c4c2259.png)

**Comment by bcoles** [comment]
> What version of SpiderFoot are you using (stable release or Git master branch)?
> Spiderfoot v3.0

This version of SpiderFoot is extremely old. [Version 3.0](https://github.com/smicallef/spiderfoot/releases/tag/v3.0) was released more than 3 years ago.

The OSINT world moves very fast. Data sources are constantly changing.

The format of the JSON file provided by [WebBreacher/WhatsMyName](https://github.com/WebBreacher/WhatsMyName/) has since changed. The `sfp_accounts` SpiderFoot module has been updated to support these changes; however, this updated version is only available in the latest version of SpiderFoot from the GitHub repository.

**Comment by armaanfarshori** [comment]
Stupid of me. Yeah it works.
