### ISSUE TITLE
Scan not initialized using SFCli

### ISSUE THREAD

**Issue by OzAven** [smicallef/spiderfoot#240]
Hi,

I'm trying to use SpiderFoot Cli yet I encounter a situation where the server responds and seems up, yet any scan im trying to initiate (Whether using a "-u" flag or using a "-m") seem stuck in early stages.

Please see the below screenshot:
![capture](https://user-images.githubusercontent.com/7952418/51546883-cd87ac00-1e6d-11e9-88da-4152f0e6ca00.JPG)

Is there anything i'm doing wrong? 
Any other testing I can apply beyond the "debug" function and pinging the SF server?

Thanks,
Oz

**Comment by smicallef** [comment]
Strange indeed.. I assume the state of the system you're running on is healthy? What if you open up a web browser to the server (http://127.0.0.1:5002) and see what the state of the scan is?

**Comment by OzAven** [comment]
Thanks for the answer yet I already uninstalled.
It didnt work appropriately and GUI prompted that there's an error in the DB and that the scan seems stuck.

________________________________

**Comment by bcoles** [comment]
I can't reproduce this error with the `-m` flag or `-u all`.

I did identify a separate error, in that the `-u` flag does not appear to be working as intended. It works for `all`, but not other user cases, such as `passive`.

> Any other testing I can apply beyond the "debug" function and pinging the SF server?

You can watch the scan progress using the `-w` watch flag to the `start` command. You can view scan progress and logs using the `logs <scan id>` command.

You can also view scan progress and scan results using the web interface. Scan logs are also available in the `Logs` tab associated with the scan.

Application error logs are written to `sferror.log` in the Spiderfoot root directory.

You could try initiating the scan from the web interface, rather than the CLI, and see if that makes a difference.
