### ISSUE TITLE
Feature Request: Easy APIs registration

### ISSUE THREAD

**Issue by aress31** [smicallef/spiderfoot#382]
It would be great if paid members of SpiderFoot HX could be given the option/feature to register for all the different API keys used by the different modules in one go.

For example, paid members could be asked to provide an email, username and password that will then be used to automatically/transparently register to the relevant websites and print back all the different API keys.

This option would definitely set SpiderFoot HX apart from the competitors.

**Comment by smicallef** [comment]
Something even better to this is being worked on... watch this space :)

**Comment by AresS31** [comment]
@smicallef now that you started you got to spill the beans! :)

**Comment by smicallef** [comment]
Going to close this, since it turned out to not really be feasible given the vast array of APIs and uniqueness of their registration approaches. There is still something along these lines planned for HX but it's low priority among some of the bigger things that have been shipped and are being worked on.
