### ISSUE TITLE
ModuleNotFoundError: No module named 'cherrypy

### ISSUE THREAD

**Issue by KushaiDob** [smicallef/spiderfoot#464]
Hello.

when you run the command "python3 sf.py" an error occurs "ModuleNotFoundError: No module named 'cherrypy' "
how to solve it?

**Comment by bcoles** [comment]
Try `pip3 install -r requirements.txt`

**Comment by smicallef** [comment]
This is basically the standard problem when you are using `pip` to install the dependencies and not `pip3`. If you use `pip3` they will be available to Python 3 and therefore SpiderFoot will work fine.

**Comment by duffman437** [comment]
Hi there,

I typed in the required lines verbatim but I still got that error, is there something else I can do or something I may have missed? it seems straight forward.

**Comment by bcoles** [comment]
> 
> 
> Hi there,
> 
> I typed in the required lines verbatim but I still got that error, is there something else I can do or something I may have missed? it seems straight forward.

It is likely that you have multiple versions of Python installed. Ensure you are using Python 3. Ensure you are using the same version.

For example:

```
pip3.8 install -r requirements.txt
python3.8 sf.py
```

**Comment by wolfhead74** [comment]
I know this was from last year but I just had the exact same issue as this so I just ran the pip3 install...... command again and it seemed to grab more files so looks like it did not complete the first time through.  After that it launched perfectly.

**Comment by anipaul2** [comment]
I'm getting a issue at cherrpy module as it says no module found...I tried to install but still showing error.

**Comment by bcoles** [comment]
> 
> 
> I'm getting a issue at cherrpy module as it says no module found...I tried to install but still showing error.

Make use you're using the same version of pip to install dependencies as the version of Python you're using.

https://github.com/smicallef/spiderfoot/issues/464#issuecomment-732763767

**Comment by anipaul2** [comment]
solved now thanks

**Comment by Lycan48** [comment]
Hello, I am having the same issue. Trying to run spiderfoot

**Comment by bcoles** [comment]
> Hello, I am having the same issue. Trying to run spiderfoot

https://github.com/smicallef/spiderfoot/issues/464#issuecomment-732763767

**Comment by Lycan48** [comment]
> > Hi there,
> > I typed in the required lines verbatim but I still got that error, is there something else I can do or something I may have missed? it seems straight forward.
> 
> It is likely that you have multiple versions of Python installed. Ensure you are using Python 3. Ensure you are using the same version.
> 
> For example:
> 
> ```
> pip3.8 install -r requirements.txt
> python3.8 sf.py
> ```

I used same but nothing worked same issue

**Comment by peetzafox** [comment]
I found a fix.

Navigate to your spiderfoot directory.
Open _./sf.py_ in an editor, and have a look at the script's first line.
If you see **`#!/usr/bin/env python3`**, highlight and delete that line from the script.
Save the change to _./sf.py_.
Try running spiderfoot again.

If nothing changed for you, undo the change you made.

**Comment by peetzafox** [comment]
> I used same but nothing worked same issue

The following fix worked for me after previous solutions failed to fix the issue ...

Navigate to your spiderfoot directory.
Open _sf.py_ in an editor, and have a look at the script's first line.
If you see **`#!/usr/bin/env python3`**, highlight and delete that line from the script.
Save changes to _sf.py_.
Try running spiderfoot again.

If nothing changed for you, undo the change you made.

The issue **`#!/usr/bin/env python3`** was causing for me ... was that it configured the interpreter to import modules from a completely different directory.

My current (main) Python setup is located at **`~\AppData\Local\Programs\Python\Python312`**, and modules are typically pulled from **`~\AppData\Local\Programs\Python\Python312\Lib\site-packages`**. However, when _sf.py_ is initiated, the shebang causes my interpeter to import modules from **`C:\msys64\ucrt64\lib\python3.12\site-packages`**.

So, if your issue is similar to what mine was -- removing **`#!/usr/bin/env python3`** from _sf.py_ will allow it to import modules normally again.
