### ISSUE TITLE
Docker installation in Spiderfoot 3.0 release fails

### ISSUE THREAD

**Issue by sqall01** [smicallef/spiderfoot#541]
Hi,
I just downloaded spiderfoot 3.0 release to test it. I followed the instructions [here](https://www.spiderfoot.net/a-simpler-way-to-get-spiderfoot-running-is-to-use-docker/) to build the docker container. Everything went fine there. However, when I want to start the container I get the following:

```
➜  spiderfoot-3.0 docker run --rm -p 5009:5001 spiderfoot                                  
Traceback (most recent call last):
  File "./sf.py", line 21, in <module>
    import cherrypy
  File "/usr/lib/python3.8/site-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/usr/lib/python3.8/site-packages/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "/usr/lib/python3.8/site-packages/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
  File "/usr/lib/python3.8/site-packages/jaraco/collections.py", line 9, in <module>
    import jaraco.text
  File "/usr/lib/python3.8/site-packages/jaraco/text/__init__.py", line 8, in <module>
    import six
ModuleNotFoundError: No module named 'six'
´´´

So my guess is, that somewhere during the build was the requirement not installed.

**Comment by sibtcha** [comment]
Same for me :-(

**Comment by Douglas1701** [comment]
I am also experiencing this issue.

**Comment by Sucramx** [comment]
The latest alpine image is the problem. There is a compatibility issue that is currently being worked on. The Dockerfile is using apline:latest which pulls the latest apline image(the broken one). If you open up the Dockerfile and change it to apline:3.9.6, and than build the spiderfoot image it should work not problem 😃 

`#
# Spiderfoot Dockerfile
#
# http://www.spiderfoot.net
#
# Written by: Michael Pellon <m@pellon.io>
# Updated by: Chandrapal <bnchandrapal@protonmail.com>
# Updated by: Steve Micallef <steve@binarypool.com>
#    -> Inspired by https://github.com/combro2k/dockerfiles/tree/master/alpine-spiderfoot
#
# Usage:
#
#   sudo docker build -t spiderfoot .
#   sudo docker run -it -p 5001:5001 spiderfoot

# Pull the base image.
FROM alpine:3.9.6
COPY requirements.txt .

# Run everything as one command so that only one layer is created
RUN apk --update add --no-cache --virtual build-dependencies gcc git curl py3-pip swig \
        tinyxml-dev python3-dev musl-dev openssl-dev libffi-dev libxslt-dev \
    && apk --update --no-cache add python3 musl openssl libxslt tinyxml jpeg-dev openjpeg-dev zlib-dev \
    && pip3 --no-cache-dir install wheel \
    && pip3 --no-cache-dir install -r requirements.txt \
    && addgroup spiderfoot \
    && adduser -G spiderfoot -h /home/spiderfoot -s /sbin/nologin \
               -g "SpiderFoot User" -D spiderfoot \
    && rmdir /home/spiderfoot \
    && cd /home \
    && curl -sSL https://github.com/smicallef/spiderfoot/archive/v3.0.tar.gz \
       | tar -v -C /home -xz \
    && mv /home/spiderfoot-3.0 /home/spiderfoot \
    && chown -R spiderfoot:spiderfoot /home/spiderfoot \
    && apk del --purge build-dependencies \
    && rm -rf /var/cache/apk/* \
    && rm -rf /root/.cache

USER spiderfoot
WORKDIR /home/spiderfoot

EXPOSE 5001

# Run the application.
ENTRYPOINT ["/usr/bin/python3"] 
CMD ["./sf.py", "-l", "0.0.0.0:5001"]
`

**Comment by alphaDev23** [comment]
I hit the same issue.  @Sucramx, thank you for the solution.

It should be noted that best practice is to use a specific base image:tag (other than latest) to avoid compatibility issues such as this.

**Comment by lprat** [comment]
The problem isn't latest alpine image, but "apk del --purge build-dependencies" -> remove py3.six and other lib.
Remove this line and use latest alpine.

**Comment by steve-bate** [comment]
It works with the older alpine image, so based on that evidence, it's at least *related* to the alpine image version. Not removing build dependencies is an interesting workaround but would result in a larger image, possibly a much larger image. I suppose we could remove build dependencies and then reinstall the `six` package and other necessary runtime packages to support the newer alpine version.

**Comment by lprat** [comment]
you are right, it is also the best solution (remove build dependencies and then reinstall the six package and other necessary)
