### ISSUE TITLE
sfscan.py:134:13: F841 local variable 'socksDns' is assigned to but never used

### ISSUE THREAD

**Issue by bcoles** [smicallef/spiderfoot#880]
```
$ grep -rn socksDns *.py
sfscan.py:134:            socksDns = self.__config['_socks6dns']
```

```
$ grep -rn socks6dns *.py
sf.py:61:    '_socks6dns': True,
sf.py:79:    '_socks6dns': "Resolve DNS through the SOCKS proxy? When SOCKS/TOR is used this will always be True when resolving to fetch web content. Otherwise, all other DNS resolution goes to your configured DNS server.",
sfscan.py:134:            socksDns = self.__config['_socks6dns']
```

**Comment by smicallef** [comment]
Looks like this got picked up in one of your many clean-ups, so closing.

**Comment by smicallef** [comment]
Re-opening, I grepped for the wrong thing. This may be a relic from an older SOCKS python library that was used. Thinking about it, the only benefit of this option is to explicitly disable routing DNS through SOCKS/TOR when you are using SOCKS/TOR for other traffic. If that turns out to be the case, we could just drop this option but it needs further investigation.

**Comment by bcoles** [comment]
> This may be a relic from an older SOCKS python library that was used.

yes

> Thinking about it, the only benefit of this option is to explicitly disable routing DNS through SOCKS/TOR when you are using SOCKS/TOR for other traffic.

yes, that is what the variable name implies

yes, that is the intended use case

> but it needs further investigation.

yes
