### ISSUE TITLE
sfp_ahmia fullnames option is not respecting it's state

### ISSUE THREAD

**Issue by Sucramx** [smicallef/spiderfoot#921]
By default the module sfp_ahmia searches only fullnames.
Example: "John Smith".
I would like to be able to search sfp_ahmia with only a first name or last name.
Example: "John".

Spiderfoot provides a option to to this by setting the fullnames boolean to false for the module sfp_ahmia.
The issue is when I change the option to false, spiderfoot does not respect the state of that option and it remains true inside the script.

Thus when sending sfp_ahmia a Human_Name with only a first name or last name, it yields no results due to the following piece of code:

` if not self.opts['fullnames'] and eventName == 'HUMAN_NAME':
       return None`

**Comment by smicallef** [comment]
Not sure I follow.. that logic you point out is correct: if you are not wanting to search for full names and the event the module is processing is a human name, then do nothing.

What actually /might/ be happening is that searching for a name without a space in it results in SpiderFoot not treating your target as a name at all, since SpiderFoot expects a quoted name to contain a space, and instead getting treated as a username, which no modules search the dark web for (would be too many false positives).
