### ISSUE TITLE
Infinite Scan Loading 

### ISSUE THREAD

**Issue by MiChaelinzo** [smicallef/spiderfoot#972]
<img width="299" alt="spiderfoot" src="https://user-images.githubusercontent.com/68110223/92249176-54b65600-eed2-11ea-8fed-472e467ad7aa.PNG">
updated to the latest v3.3-DEV, installed all requirments.
New Scan and Settings are working perfectly except the Scans tab.

**Comment by bcoles** [comment]
Does the page work after reloading the page?

What operating system and version of Python are you using?

Do you receive any errors in the browser console? Do any of the network requests result in a HTTP 500 error?

Do you receive any errors in the terminal?

**Comment by MiChaelinzo** [comment]
> Does the page work after reloading the page?
> 
> What operating system and version of Python are you using?
> 
> Do you receive any errors in the browser console? Do any of the network requests result in a HTTP 500 error?
> 
> Do you receive any errors in the terminal?

Nope it doesn't work after reloading the page 
GNU/Linux Rolling 
Nope, no browser and terminal error or notifications.
btw is there benefit in running it on sudo etc.?
<img width="710" alt="spiderfoot1" src="https://user-images.githubusercontent.com/68110223/92272527-61e33d00-eef2-11ea-9e2f-565c2b27a5a7.PNG">

**Comment by bcoles** [comment]
> updated to the latest v3.3-DEV

Is this part of the Kali package? Or are you using SpiderFoot from the `master` branch?

> Nope, no browser and terminal error or notifications.

This error is *usually* due to either a JavaScript error or the server returning an unexpected reply (ie, HTTP 500 error) which the front end JavaScript can't parse.

Strange that there's no errors in the browser console. Can you show a screenshot of the network requests in the web dev tools when you click `Scans`.

**Comment by bcoles** [comment]
> btw is there benefit in running it on sudo etc.?

`sudo` privileges shouldn't be required, so long as you're binding to a non-privileged port > 1024. Port 6969 is fine.

If you've been using the GitHub `master` branch for a while, when did you start to encounter this error?

There were some changes made with logging recently. SpiderFoot should drop a `spiderfoot.error.log` (and `spiderfoot.debug.log` if debugging is enabled) to the SpiderFoot working directory. Maybe your filesystem permissions don't allow this and the error is being silently swallowed. I wouldn't imagine that's the case, as SpiderFoot also writes to `spiderfoot.db` which is also located in the working directory.

**Comment by MiChaelinzo** [comment]
> > updated to the latest v3.3-DEV
> 
> Is this part of the Kali package? Or are you using SpiderFoot from the `master` branch?
> 
> > Nope, no browser and terminal error or notifications.
> 
> This error is _usually_ due to either a JavaScript error or the server returning an unexpected reply (ie, HTTP 500 error) which the front end JavaScript can't parse.
> 
> Strange that there's no errors in the browser console. Can you show a screenshot of the network requests in the web dev tools when you click `Scans`.

Yeah master branch I just git pull earlier for update. I encountered this problem since 3.2-DEV. 
I can get the the latest release 3.2 working just fine and dandy https://github.com/smicallef/spiderfoot/releases.  

<img width="605" alt="spiderfoot2" src="https://user-images.githubusercontent.com/68110223/92278342-b3dd9000-eefd-11ea-80c9-ef8903e0d019.PNG">

I just don't understand why the DEV versions won't work for me....

**Comment by MiChaelinzo** [comment]
Here is my sf debug and error log...
[spiderfoot.debug.log](https://github.com/smicallef/spiderfoot/files/5176639/spiderfoot.debug.log)
[spiderfoot.error.log](https://github.com/smicallef/spiderfoot/files/5176640/spiderfoot.error.log)

**Comment by bcoles** [comment]
> I encountered this problem since 3.2-DEV.

3.3-DEV has a lot of changes since 3.2 release, but nothing that should be causing that issue.

Most development and testing was also done on Kali.

You're probably in a better position to play spot-the-difference than I am, as I can't reproduce this issue.

I'd still like to see a screenshot of the browser dev console showing the network requests. In particular, requests to `/scanlist`. It should return JSON content with `Content-Type: application/json; charset=utf-8`.

The debug logs show no server-side errors, indicating that client side JavaScript is likely to be the problem.

If you take a look in `static/js/spiderfoot.js` and remove the `sf.log(message);` call from the `sf.genericError` function at the top of the file, maybe that will help. Like this:

```javascript
sf.genericError = function(message) {
    alert("Failure: " + message);
}
```

**Comment by bcoles** [comment]
Also, if you go into Settings and enable debug output that will enable debug output in scan logs and the terminal. That may offer some insight.

![image](https://user-images.githubusercontent.com/434827/92297999-0b284280-ef88-11ea-8c57-e4abd0f22c98.png)

**Comment by bcoles** [comment]
Dupe of #949
